spring:
  liquibase:
    defaultSchema: ${schema:TMS}
    change-log: classpath:db.migration/master.yaml

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    password: sa
  jpa:
    properties:
      hibernate:
        default_schema: ${schema:TMS}
        hbm2ddl:
          auto: validate
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  mvc:
    servlet:
      path: /api/v1
